"""
skills/outreach/email_templates.py
===================================
DEPRECATED -- kept for backwards compatibility only.
The canonical template is now at: templates/email/cold_outreach.py

Do not edit this file. Edit templates/email/cold_outreach.py instead.
"""
from templates.email.cold_outreach import SUBJECT as COLD_OUTREACH_SUBJECT, BODY as COLD_OUTREACH_TEMPLATE

__all__ = ['COLD_OUTREACH_SUBJECT', 'COLD_OUTREACH_TEMPLATE']
