"""
doc_routing_crew.py — Crew assembly for document taxonomy and routing.

Called by orchestrator.py when task_type == "doc_routing".
The crew runs a single TaxonomyRoutingAgent task and returns
a JSON classification decision in TaskResponse.result.
"""

import os
import json
import logging
import time
from typing import Optional
from crewai import Crew, Task, Process

logger = logging.getLogger(__name__)

REGISTRY_SHEET_ID = os.environ.get("NOTEBOOKLM_REGISTRY_SHEET_ID", "")
ROUTING_MATRIX_CACHE: dict = {"rows": [], "fetched_at": 0.0}
CACHE_TTL_SECONDS = 300  # 5 minutes


def _get_routing_matrix() -> list[dict]:
    """
    Fetch routing matrix from Registry Sheet, with 5-minute in-memory cache.
    Falls back to seed defaults if sheet ID is not configured or fetch fails.
    """
    from skills.doc_routing.taxonomy_agent import parse_routing_matrix, ROUTING_MATRIX_SEED
    from skills.doc_routing.gws_cli_tools import GWSSheetsReadRangeTool

    now = time.time()
    if ROUTING_MATRIX_CACHE["rows"] and (now - ROUTING_MATRIX_CACHE["fetched_at"]) < CACHE_TTL_SECONDS:
        return ROUTING_MATRIX_CACHE["rows"]

    if not REGISTRY_SHEET_ID:
        logger.warning("NOTEBOOKLM_REGISTRY_SHEET_ID not set -- using seed routing matrix")
        return ROUTING_MATRIX_SEED

    try:
        tool = GWSSheetsReadRangeTool()
        raw = tool._run(json.dumps({"spreadsheet_id": REGISTRY_SHEET_ID, "range": "Routing Matrix!A:G"}))
        data = json.loads(raw)
        if "error" in data:
            raise ValueError(data["error"])
        rows = parse_routing_matrix(data.get("values", []))
        if rows:
            ROUTING_MATRIX_CACHE["rows"] = rows
            ROUTING_MATRIX_CACHE["fetched_at"] = now
            return rows
    except Exception as e:
        logger.error(f"Failed to fetch routing matrix from Sheets: {e} -- using seed")
    return ROUTING_MATRIX_SEED


def build_doc_routing_crew(user_request: str, context: Optional[dict] = None) -> Crew:
    """
    Build a single-agent crew for document taxonomy and routing.

    context dict fields (all required):
      record_id      -- UUID pre-generated by n8n
      filename       -- original filename
      extracted_text -- first 500 words (empty string if unreadable)
      mime_type      -- file MIME type
      source         -- "agent-generated" | "manual-upload"
      project_hint   -- project ID string or None
    """
    from skills.doc_routing.taxonomy_agent import build_taxonomy_routing_agent

    ctx = context or {}
    record_id = ctx.get("record_id", "unknown")
    filename = ctx.get("filename", "unknown")
    extracted_text = ctx.get("extracted_text", "")
    mime_type = ctx.get("mime_type", "unknown")
    source = ctx.get("source", "manual-upload")
    project_hint = ctx.get("project_hint", None)

    routing_matrix = _get_routing_matrix()
    agent = build_taxonomy_routing_agent(routing_matrix)

    task = Task(
        description=f"""Classify and route the following document.

RECORD ID: {record_id}
FILENAME: {filename}
MIME TYPE: {mime_type}
SOURCE: {source}
PROJECT HINT: {project_hint or "none"}

EXTRACTED TEXT (first 500 words):
{extracted_text or "(no text extracted -- treat as unreadable)"}

Apply the routing matrix (embedded in your instructions) to determine:
1. The correct domain and target folder path
2. The standardized filename following the naming convention
3. The notebook assignment (use only the five controlled values)
4. The confidence score and whether to auto-file or send for review

Output ONLY the JSON object described in your instructions. No other text.""",
        expected_output=(
            "A single valid JSON object with all required fields: record_id, domain, "
            "topic_or_client, doc_type, target_folder_path, standardized_filename, "
            "project_id, new_project_name, notebook_assignment, confidence, "
            "confidence_score, review_required, auto_file, routing_notes."
        ),
        agent=agent,
    )

    crew = Crew(
        agents=[agent],
        tasks=[task],
        process=Process.sequential,
        verbose=False,
        memory=False,
    )
    return crew


def run_doc_routing_with_retry(user_request: str, context: Optional[dict] = None) -> dict:
    """
    Run the doc routing crew with one retry on failure.

    On first failure: wait 30 seconds, rebuild crew, try once more.
    On second failure: return a fallback classification that routes to Review Queue.
    Called by the orchestrator instead of crew.kickoff() directly.
    """
    import time as _time
    import json as _json

    filename = (context or {}).get("filename", "unknown")
    record_id = (context or {}).get("record_id", "unknown")

    fallback = {
        "record_id": record_id,
        "domain": "OPS",
        "topic_or_client": "Unknown",
        "doc_type": "reference",
        "target_folder_path": "00_Review_Queue/",
        "standardized_filename": f"OPS_unknown_reference_{record_id[:8]}",
        "project_id": "OP-001",
        "new_project_name": None,
        "notebook_assignment": "Unassigned",
        "confidence": "low",
        "confidence_score": 0.0,
        "review_required": True,
        "auto_file": False,
        "routing_notes": "LLM call failed after retry. Routed to Review Queue.",
    }

    for attempt in range(2):
        try:
            crew = build_doc_routing_crew(user_request, context=context)
            result = crew.kickoff()
            result_str = str(result).strip()
            # Strip any markdown code fences the LLM may have added
            if result_str.startswith("```"):
                result_str = result_str.split("```")[1]
                if result_str.startswith("json"):
                    result_str = result_str[4:]
            return _json.loads(result_str)
        except Exception as e:
            logger.error(f"doc_routing attempt {attempt + 1} failed: {e}")
            if attempt == 0:
                logger.info("Retrying doc_routing after 30 seconds...")
                _time.sleep(30)

    # Both attempts failed -- send Telegram alert and return fallback
    try:
        from notifier import send_message
        import os
        chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
        if chat_id:
            send_message(chat_id, f"Classification failed for {filename}. Routed to Review Queue.")
    except Exception:
        pass

    return fallback
