#!/bin/bash
set -e

# vercel-launch/scripts/launch.sh
# Usage: bash launch.sh <base-name> [--prod]
# Outputs JSON to stdout. Progress to stderr.

# ── Args ────────────────────────────────────────────────────────────────────
BASE_NAME="${1:-}"
PROD=false

if [[ -z "$BASE_NAME" ]]; then
  echo '{"error":"Missing app name. Usage: launch.sh <base-name> [--prod]"}' >&1
  exit 1
fi

shift
for arg in "$@"; do
  [[ "$arg" == "--prod" ]] && PROD=true
done

# ── Normalize name ───────────────────────────────────────────────────────────
# lowercase, spaces to hyphens, strip trailing -app if user included it
APP_BASE=$(echo "$BASE_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g' | sed 's/-app$//')
APP_NAME="${APP_BASE}-app"

echo "App name: $APP_NAME" >&2

# ── Detect agentsHQ root ─────────────────────────────────────────────────────
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OS" == "Windows_NT" ]]; then
  AGENTS_ROOT="D:/Ai_Sandbox/agentsHQ"
else
  AGENTS_ROOT="/root/agentsHQ"
fi

echo "agentsHQ root: $AGENTS_ROOT" >&2

# ── Locate app folder ────────────────────────────────────────────────────────
APP_DIR="$AGENTS_ROOT/output/apps/$APP_NAME"

if [[ ! -d "$APP_DIR" ]]; then
  echo "Creating app folder: $APP_DIR" >&2
  mkdir -p "$APP_DIR"
fi

# ── Find VERCEL_TOKEN ─────────────────────────────────────────────────────────
find_token() {
  local search_paths=("$APP_DIR/.env" "$AGENTS_ROOT/.env" "$HOME/.env")
  for f in "${search_paths[@]}"; do
    if [[ -f "$f" ]]; then
      local token
      token=$(grep -E '^VERCEL_TOKEN=' "$f" 2>/dev/null | head -1 | cut -d= -f2-)
      if [[ -n "$token" ]]; then
        echo "$token"
        return 0
      fi
    fi
  done
  return 1
}

VERCEL_TOKEN=$(find_token) || {
  echo '{"error":"VERCEL_TOKEN not found in any .env file"}' >&1
  exit 1
}

echo "Token found." >&2

# ── Check / create GitHub repo ───────────────────────────────────────────────
REPO_OWNER="bokar83"
REPO_FULL="$REPO_OWNER/$APP_NAME"

echo "Checking GitHub repo: $REPO_FULL" >&2

if gh repo view "$REPO_FULL" &>/dev/null; then
  echo "Repo already exists." >&2
else
  echo "Creating public GitHub repo: $REPO_FULL" >&2
  gh repo create "$REPO_FULL" --public --description "App: $APP_NAME" --confirm 2>/dev/null || \
  gh repo create "$REPO_FULL" --public --description "App: $APP_NAME" 2>&1 >&2
fi

REPO_URL="https://github.com/$REPO_FULL"

# ── Git init + push ───────────────────────────────────────────────────────────
cd "$APP_DIR"

if [[ ! -d ".git" ]]; then
  echo "Initializing git repo..." >&2
  git init
  git checkout -b main 2>/dev/null || git checkout main 2>/dev/null || true

  # Add .gitignore if missing
  if [[ ! -f ".gitignore" ]]; then
    cat > .gitignore << 'EOF'
node_modules/
.env
.env.local
.env*.local
.next/
dist/
build/
.vercel/
*.log
EOF
  fi

  # Create placeholder if folder is empty
  if [[ -z "$(ls -A . 2>/dev/null | grep -v .git | grep -v .gitignore)" ]]; then
    echo "# $APP_NAME" > README.md
    echo "App scaffold — generated by vercel-launch" >> README.md
  fi

  git add -A
  git commit -m "init: scaffold $APP_NAME"
  git remote add origin "git@github.com:$REPO_FULL.git" 2>/dev/null || \
    git remote set-url origin "git@github.com:$REPO_FULL.git"
  git push -u origin main
  echo "Git pushed to main." >&2
else
  echo "Git repo exists. Checking for unpushed changes..." >&2
  if [[ -n "$(git status --porcelain)" ]]; then
    git add -A
    git commit -m "deploy: update $APP_NAME"
    git push
    echo "Changes pushed." >&2
  else
    echo "Nothing to commit." >&2
  fi
fi

# ── Vercel link ───────────────────────────────────────────────────────────────
if [[ ! -f ".vercel/project.json" && ! -f ".vercel/repo.json" ]]; then
  echo "Linking to Vercel..." >&2
  vercel link --repo --token "$VERCEL_TOKEN" --yes 2>&1 >&2 || \
  vercel link --token "$VERCEL_TOKEN" --yes 2>&1 >&2
  echo "Vercel linked." >&2
else
  echo "Already linked to Vercel." >&2
fi

# ── Deploy ────────────────────────────────────────────────────────────────────
echo "Deploying to Vercel..." >&2

DEPLOY_ARGS="--token $VERCEL_TOKEN --yes --no-wait"
if [[ "$PROD" == "true" ]]; then
  DEPLOY_ARGS="$DEPLOY_ARGS --prod"
  echo "Target: PRODUCTION" >&2
else
  echo "Target: preview" >&2
fi

DEPLOY_OUTPUT=$(vercel deploy $DEPLOY_ARGS 2>&1)
PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -Eo 'https://[^ ]+\.vercel\.app' | head -1)

if [[ -z "$PREVIEW_URL" ]]; then
  PREVIEW_URL="Check https://vercel.com/dashboard for deployment status"
fi

# ── Output JSON ───────────────────────────────────────────────────────────────
cat <<EOF
{
  "appName": "$APP_NAME",
  "repoUrl": "$REPO_URL",
  "previewUrl": "$PREVIEW_URL",
  "production": $PROD
}
EOF
