#!/usr/bin/env pwsh
# worktree_status_report.ps1 -- read-only status of all agentsHQ worktrees.
#
# For each worktree under D:/Ai_Sandbox/agentsHQ-worktrees/, report:
#   - branch
#   - dirty (count of uncommitted/untracked files)
#   - unpushed (commits ahead of origin)
#   - mtime age (days since latest file change in worktree)
#   - origin status: merged-to-main? branch exists? deleted on origin?
#   - junction: does D:/tmp/wt-X junction still point here?
#
# Output: console table + markdown summary at
#   D:/Ai_Sandbox/agentsHQ/docs/audits/worktree-status-YYYY-MM-DD.md
#
# Does NOT delete anything. Read-only. Surface candidates for kill.
# Schedule: weekly Windows Task Scheduler. Tighten cadence if junction
# count grows past ~30.
#
# 2026-05-16: created per Council "ship-with-changes" verdict.
# Reason for read-only: deletion of an unused-looking worktree is the
# operation most likely to surprise you later when scratch state matters.
# Manual ack via Telegram digest is the planned next phase; not built yet.

$ErrorActionPreference = 'Continue'
$canonical = 'D:/Ai_Sandbox/agentsHQ'
$wtRoot = 'D:/Ai_Sandbox/agentsHQ-worktrees'
$junctionRoot = 'D:/tmp'
$today = Get-Date -Format 'yyyy-MM-dd'
$reportPath = "$canonical/docs/audits/worktree-status-$today.md"

if (-not (Test-Path $wtRoot)) {
  Write-Output "no worktrees at $wtRoot"
  exit 0
}

git -C $canonical fetch origin --prune 2>&1 | Out-Null
$mainSha = (git -C $canonical rev-parse origin/main).Trim()

$rows = @()
foreach ($wt in (Get-ChildItem $wtRoot -Directory | Sort-Object Name)) {
  $path = $wt.FullName
  $name = $wt.Name
  $branch = (git -C $path rev-parse --abbrev-ref HEAD 2>$null).Trim()
  if (-not $branch) { continue }

  $dirty = (git -C $path status --porcelain 2>$null | Measure-Object -Line).Lines
  $unpushed = 0
  try { $unpushed = (git -C $path log '@{u}..HEAD' --oneline 2>$null | Measure-Object -Line).Lines } catch {}

  # mtime age: most recent file mtime in the worktree (excluding .git)
  $newest = Get-ChildItem $path -Recurse -File -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch '\\\.git\\' } |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
  $ageDays = if ($newest) { [int]((Get-Date) - $newest.LastWriteTime).TotalDays } else { 999 }

  # Origin status
  $originRef = "refs/remotes/origin/$branch"
  $originExists = $false
  try { $originSha = (git -C $canonical rev-parse $originRef 2>$null).Trim(); $originExists = -not [string]::IsNullOrEmpty($originSha) } catch {}
  $mergedToMain = $false
  if ($originExists) {
    $tipSha = (git -C $path rev-parse HEAD).Trim()
    $isAncestor = git -C $canonical merge-base --is-ancestor $tipSha $mainSha 2>$null
    $mergedToMain = ($LASTEXITCODE -eq 0)
  }

  # Junction at old D:/tmp/wt-X?
  $jct = "$junctionRoot/$name"
  $jctExists = Test-Path $jct
  $jctTarget = if ($jctExists) { (Get-Item $jct -ErrorAction SilentlyContinue).Target } else { $null }
  $jctOk = ($jctExists -and $jctTarget -eq ($path -replace '/','\'))

  # Candidate-for-kill signal: merged + 0 dirty + 0 unpushed + age > 14d
  $killable = ($mergedToMain -and $dirty -eq 0 -and $unpushed -eq 0 -and $ageDays -gt 14)

  $rows += [PSCustomObject]@{
    WT = $name
    Branch = $branch
    Dirty = $dirty
    Unpushed = $unpushed
    AgeDays = $ageDays
    OriginExists = if ($originExists) { 'yes' } else { 'NO' }
    Merged = if ($mergedToMain) { 'yes' } else { '-' }
    Junction = if ($jctOk) { 'ok' } elseif ($jctExists) { 'wrong-target' } else { 'missing' }
    Killable = if ($killable) { 'YES' } else { '-' }
  }
}

$rows | Format-Table -AutoSize

# Write markdown report
if (-not (Test-Path "$canonical/docs/audits")) { New-Item -ItemType Directory -Path "$canonical/docs/audits" -Force | Out-Null }
$md = @()
$md += "# Worktree Status Report - $today"
$md += ""
$md += "Generated by `scripts/worktree_status_report.ps1` (read-only)."
$md += "Worktrees living at `D:/Ai_Sandbox/agentsHQ-worktrees/` per canonical-sibling rule (2026-05-16 path update)."
$md += ""
$md += "| WT | Branch | Dirty | Unpushed | AgeDays | OriginExists | Merged | Junction | Killable |"
$md += "|---|---|---:|---:|---:|---|---|---|---|"
foreach ($r in $rows) {
  $md += "| $($r.WT) | $($r.Branch) | $($r.Dirty) | $($r.Unpushed) | $($r.AgeDays) | $($r.OriginExists) | $($r.Merged) | $($r.Junction) | $($r.Killable) |"
}
$md += ""
$md += "## Kill candidates"
$md += ""
$kc = $rows | Where-Object { $_.Killable -eq 'YES' }
if (-not $kc) {
  $md += "_None._ All worktrees still have dirty WIP, unpushed commits, unmerged branches, or recent activity."
} else {
  $md += "These worktrees are merged-to-main AND clean AND >14d old. Candidates for archive/delete."
  $md += "Manual review before deletion. Branch already on origin = work survives deletion of local worktree."
  foreach ($r in $kc) {
    $md += "- ``$($r.WT)`` (branch ``$($r.Branch)``, age $($r.AgeDays)d)"
  }
}
$md += ""
$md += "## Junction health"
$md += ""
$jb = $rows | Where-Object { $_.Junction -ne 'ok' }
if (-not $jb) {
  $md += "_All junctions ok._"
} else {
  foreach ($r in $jb) {
    $md += "- ``D:/tmp/$($r.WT)`` -> $($r.Junction)"
  }
}
$md -join "`n" | Out-File -FilePath $reportPath -Encoding utf8
Write-Output ""
Write-Output "Report: $reportPath"
